# Generated by Django 4.1.6 on 2023-02-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Diesel', 'Diesel'), ('Regular', 'Regular')], default='Regular', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='kilometer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='observations',
            field=models.TextField(null=True),
        ),
    ]
