# Generated by Django 4.1.6 on 2023-02-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_car_fuel_type_car_kilometer_alter_car_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='observations',
            field=models.TextField(),
        ),
    ]
