# Generated by Django 4.1.6 on 2023-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_alter_car_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='observations',
            field=models.TextField(null=True),
        ),
    ]
