# Generated by Django 4.1.6 on 2023-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_car_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
